# Production environment override
services:
  php:
    build:
      context: ./api
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

  # pwa:
  #   build:
  #     context: ./pwa
  #     target: prod
  
  app:
    build:
      context: ./app
      target: prod
    volumes:
      - ./docker/templates:/etc/nginx/templates
    # ports:
    #   - "3000:80"
    environment:
      - NGINX_PORT=80 

  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
